# Generated by Django 4.2.7 on 2026-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_add_read_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="ticket_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="ticket_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-sent_at"], name="notificatio_sent_at_789d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["read", "-sent_at"], name="notificatio_read_519bf9_idx"
            ),
        ),
    ]
